name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml-version: ['4.09.1']

    steps:
      - uses: actions/checkout@v2

      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Use Node.js 12.x
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Fetch git tags
        run: git fetch --tags --force

      - name: Install esy
        run: npm install -g esy

      - name: Try to restore esy cache
        uses: actions/cache@v2
        with:
          path: ~/.esy/source
          key: source-${{ hashFiles('**/index.json') }}

      - name: Install dependencies
        run: esy install

      - name: Print esy cache
        id: print_esy_cache
        run: node .github/workflows/print-esy-cache.js

      - name: Try to restore build cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Restore node modules cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: esy dune build --release

      - name: Test
        run: |
          BISECT_ENABLE=yes esy dune runtest --force

      - name: esy release
        run: esy release

      - name: Upload artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}-release
          path: _release-${{ matrix.os }}

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Download _release
        uses: actions/download-artifact@master
        with:
          name: _release-${{ matrix.os }}
          path: _release-${{ matrix.os }}

      - name: Create MacOS zip archive
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cd _release/ubuntu-latest
          zip -r ../../query-json-darwin-x64.zip .
          cd ../..

      - name: Create Linux zip archive
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd _release/macos-latest
          zip -r ../../query-json-linux-x64.zip .
          cd ../..

      - name: Upload zip to Github release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: query-json-darwin-x64.zip
          asset_name: query-json-darwin-x64.zip
          asset_content_type: application/gzip

      - name: Upload query-json-linux-x64.zip to Github release
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: query-json-linux-x64.zip
          asset_name: query-json-linux-x64.zip
          asset_content_type: application/gzip

      - name: Publish NPM package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@davesnx"
          npm config list
          npm publish --access public
        working-directory: ./_release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
